<?php

/** @var \BenJohnsonDev\SocialLogin\Block\Form\Edit $block */

// Return early if the user does not use social login
if (!$block->isCustomerSocialLogin()) {
    return;
}
?>
<div class="social-login unlink edit-wrapper">
    <h2><?= __('Linked account') ?></h2>
    <input type="checkbox" name="unlink_social" id="unlink-social" data-role="change-password" value="1"
           title="<?= $block->escapeHtmlAttr(__('Unlink')) ?>"
        <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"/>
    <label class="label" for="unlink-social">
        <span>Unlink <?= $block->getProviderLabel() ?></span>
</div>
<script type="text/x-magento-init">
    {
        "#unlink-social": {
            "BenJohnsonDev_SocialLogin/js/unlink": {}
        }
    }
</script>
